Test / place validator tests, Fix / Place resolver and Place arguments
Eco-Map/eco-city-guide pull request #12
Opened 2024-03-11 11:40 UTC by JonasJallet

2024-03-12 13:49 UTC, VinchC commented on back-end/src/resolvers/placeResolver.ts
>      createPlace(@Args() args: CreatePlace) {
Plus besoin d'être connecté pour créer une Place ?

2024-03-12 15:12 UTC, JonasJallet commented on back-end/src/entities/user.ts
> +    console.log(`New User saved: ${savedUser.getStringRepresentation()}.`);
Hello Vincent, le console log ici présent est volontaire

2024-03-12 15:15 UTC, JonasJallet commented on back-end/src/resolvers/placeResolver.ts
>      createPlace(@Args() args: CreatePlace) {
Actuellement nous n'avons pas encore mis en place les contrôles d'accès (pas encore de gestion administration), c'est juste de la suppression de code inutile pour l'instant.

2024-03-12 15:52 UTC, VinchC requested changes
Salut Jonas.

2024-03-12 15:55 UTC, VinchC approved these changes
Salut Jonas.
Bravo au nom de nous trois pour cette belle PR!

2024-03-13 08:52 UTC, PaulineHavez approved these changes
Good Job !

2024-03-13 08:58 UTC, merged