Feat/ec 43 logout route
Eco-Map/eco-city-guide pull request #39
Opened 2024-06-12 15:54 UTC by VinchC

This pull request encompasses the signOut and the deleteUser functions.

Both are currently implemented in the Initials component.

Code in relation to signOut is supposed to be copied in the /settings page.

DeleteUser might be moved completely in the /settings page and then deleted in the Initials component, unless we decide to let the "delete account" functionality in the modal, where it has been added for the phase of test before PR.

2024-06-12 20:54 UTC, JonasJallet commented on back-end/src/entities/user.ts
> +      await UserSession.deleteSession(session);
maybe you can change that for deleteSessions and give all sessions for not make the loop into the resolver but in the method

2024-06-12 21:04 UTC, JonasJallet requested changes
<img src="https://media4.giphy.com/media/YYht2UTV41u1vxHTss/giphy-downsized-medium.gif"/>

2024-06-12 21:04 UTC, JonasJallet commented on web-app/src/components/home/Initials.tsx
why do you put the delete action on this modal ? and if you do that maybe a better way for having a confirm action about delete account because user can make "missclick"

2024-06-13 08:49 UTC, VinchC commented on back-end/src/entities/user.ts
> +      await UserSession.deleteSession(session);
Done

2024-06-13 08:49 UTC, VinchC commented on back-end/src/entities/userSession.ts
> +  static async getUserSessionByUserId(userId: string): Promise<UserSession> {
Done as well

2024-06-13 08:49 UTC, JonasJallet approved these changes
<img src="https://media4.giphy.com/media/l3q2LH45XElELRzRm/giphy.gif"/>

2024-06-13 08:49 UTC, VinchC commented on web-app/src/components/home/Initials.tsx
Indeed

2024-06-13 08:50 UTC, PaulineHavez approved these changes
Great job !

2024-06-13 08:55 UTC, merged