Feat/ec 39 profil setting page
Eco-Map/eco-city-guide pull request #42
Opened 2024-06-13 13:40 UTC by PaulineHavez

**Feature setting Page :**

- update data User form
- favoris
- settings : confidential data & delete account

**Do you need to restart dataBase ?**  : yes

2024-06-13 14:16 UTC, JonasJallet requested changes
<img src="https://media0.giphy.com/media/3ohc1ffY03hnhRUyUU/giphy.gif"/>

2024-06-13 14:16 UTC, JonasJallet commented on back-end/src/types/user.args.ts
> +  @Field()///{nullable : true} pour rendre le champ optionnel
delete comment

2024-06-13 14:16 UTC, JonasJallet commented on web-app/src/components/Layout.tsx
> +// import { config } from "@fortawesome/fontawesome-svg-core";
delete comment

2024-06-13 14:16 UTC, JonasJallet commented on web-app/src/components/settings/FavoriCard.tsx
you need to change all element "favori" for "favorite"

2024-06-13 14:16 UTC, JonasJallet commented on web-app/src/components/settings/FavoriCard.tsx
> +  const handleCarteClick = () => {
carte -> map

2024-06-13 14:16 UTC, JonasJallet commented on web-app/src/interfaces/setting.ts
favorite is a place so you don't need to create this interface, just use Place type

surely same about interface updateUser is just User Type

2024-06-13 14:16 UTC, JonasJallet commented on web-app/src/pages/_document.tsx
> +// pages/_document.tsx
delete comment

2024-06-13 14:16 UTC, JonasJallet commented on web-app/src/components/settings/FavoriCard.tsx
> +    try {
i think just give setPlace(favorite) all logical about newPlace is not necessary

2024-06-13 14:16 UTC, JonasJallet commented on back-end/src/entities/user.ts
> +    if (partialUser.password) {
i think you can take a better way for don't repeat if condition

2024-06-13 14:16 UTC, JonasJallet commented on back-end/src/entities/user.ts
> +    let userWithEmailUsed: null | User = null;
unnecessary declare const directly after for that await User.getUserByEmail(partialUser.email);

2024-06-13 14:16 UTC, JonasJallet commented on back-end/src/entities/user.ts
> +    if (partialUser.email) {
same you can make simplifier for all this condition (and maybe change naming const)

2024-06-13 14:22 UTC, PaulineHavez commented on back-end/src/types/user.args.ts
> +  @Field()///{nullable : true} pour rendre le champ optionnel
Done

2024-06-13 14:51 UTC, PaulineHavez commented on web-app/src/components/settings/FavoriCard.tsx
done

2024-06-13 14:53 UTC, PaulineHavez commented on web-app/src/components/Layout.tsx
> +// import { config } from "@fortawesome/fontawesome-svg-core";
done

2024-06-13 14:53 UTC, PaulineHavez commented on web-app/src/pages/_document.tsx
> +// pages/_document.tsx
done

2024-06-13 15:04 UTC, PaulineHavez commented on back-end/src/entities/user.ts
> +    if (partialUser.email) {
done

2024-06-13 15:04 UTC, PaulineHavez commented on back-end/src/entities/user.ts
> +    if (partialUser.password) {
done

2024-06-13 15:06 UTC, PaulineHavez commented on back-end/src/entities/user.ts
> +    let userWithEmailUsed: null | User = null;
done

2024-06-13 15:09 UTC, PaulineHavez commented on web-app/src/components/settings/FavoriCard.tsx
> +    try {
done

2024-06-13 19:56 UTC, PaulineHavez commented on web-app/src/interfaces/setting.ts
For Place instead of favorite, good point :)
For updateUser I don't think it's possible to use User, which has a lot of properties (such as the role), when we've defined the UpdateUser class in the back-end with 4 properties (last name, first name, email, password).

2024-06-14 07:28 UTC, JonasJallet requested changes
<img src="https://media1.giphy.com/media/mvyvXwL26FfAtRCLPk/giphy.gif"/>

2024-06-14 07:28 UTC, JonasJallet commented on web-app/src/components/settings/FavoriCard.tsx
> +    try {
you don't need try catch

2024-06-14 07:28 UTC, JonasJallet commented on web-app/src/interfaces/setting.ts
yes i have test PartialUser but don't work, rename your interface and delete import

2024-06-14 07:32 UTC, PaulineHavez commented on web-app/src/interfaces/setting.ts
done

2024-06-14 07:39 UTC, PaulineHavez commented on back-end/src/entities/user.ts
> +    if (partialUser.password && user.hashedPassword !== partialUser.password) {
done

2024-06-14 07:39 UTC, PaulineHavez commented on back-end/src/entities/user.ts
> +    if (partialUser.email && user.email !== partialUser.email) {
done

2024-06-14 07:41 UTC, PaulineHavez commented on back-end/src/entities/user.ts
> +      if (userWithEmailAlreadyUsed !== null) {
done

2024-06-14 07:42 UTC, PaulineHavez commented on web-app/src/components/settings/SideBarSettings.tsx
> +interface SideBarSettingsProps {
done

2024-06-14 07:44 UTC, PaulineHavez commented on web-app/src/components/settings/SideBarSettings.tsx
> +const SideBarSettings: React.FC<SideBarSettingsProps> = ({
done

2024-06-14 07:45 UTC, PaulineHavez commented on web-app/src/components/settings/FavoriCard.tsx
> +    try {
done

2024-06-14 08:12 UTC, JonasJallet approved these changes
<img src="https://media4.giphy.com/media/qMi9FmYD8zXH15Fcw3/giphy.gif"/>

2024-06-14 08:13 UTC, VinchC approved these changes

2024-06-14 08:14 UTC, merged